name: Create feature-scoped dataset

on:
  workflow_dispatch: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SANITY_AUTH_TOKEN: ${{ secrets.FEATURE_DATASET_MANAGER }}
  SANITY_STUDIO_PROJECT_ID: juzvn5an
  SANITY_STUDIO_TEST_DATABASE: test

jobs:
  create-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          sparse-checkout: |
            sanity.cli.ts
            sanity.config.ts

      - name: Install Sanity
        run: | 
          yarn global add @sanity/cli
          sanity install

      - name: Delete `${{ github.ref_name }}`
        continue-on-error: true
        run: sanity dataset delete ${{ github.ref_name }} --force

      - name: Copy `production` to `${{ github.ref_name }}`
        run: sanity dataset copy production ${{ github.ref_name }} --skip-history
